spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: product-microservice-products
          uri: lb://PRODUCT-MICROSERVICE
          predicates:
            - Path=/products

        - id: product-microservice-products-wildcard
          uri: lb://PRODUCT-MICROSERVICE
          predicates:
            - Path=/products/**

        - id: product-microservice-product-id
          uri: lb://PRODUCT-MICROSERVICE
          predicates:
            - Path=/product/{id}


eureka:
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"
